name: Test
on:
  pull_request:
    branches:
      - '**'

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      fail-fast: true
    name: lint and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm ci
      - run: npm run web-components-react-wrapper:build
      - run: npm run lint
      - run: npm run app:patch:stenciljs
      - run: npm run app:build
